version: "3"

services:
  app:
    build: .
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - mongo_db
      - node_red
  node_red:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node_red:/data
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"