version: "3"

services:
  app:
    build: .
    expose:
      - "80"
      - "8000"
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"